Many bugfixes to iPhone option handling. New 'Xcode' project style for generic Xcode projects (ie Mac apps). iPhone and Xcode share some code. New --xcode-setting flag for iPhone/Xcode projects to add custom build settings. Local option handling is now a common option and has shared code in Internal/CommonOptions.

diff --git a/Unified/iPhone/Build b/Unified/iPhone/Build
--- a/Unified/iPhone/Build
+++ b/Unified/iPhone/Build
@@ -36,7 +36,7 @@ for STYLE in "${STYLES[@]}"; do
 			
 			;;
 		
-		AdHoc)
+		"Ad Hoc")
 
 			# Device, Ad Hoc
 
@@ -64,7 +64,7 @@ for STYLE in "${STYLES[@]}"; do
 
 			;;
 			
-		AppStore)
+		"App Store")
 			
 			# Device, App Store
 
@@ -89,6 +89,11 @@ for STYLE in "${STYLES[@]}"; do
 				"${ACTIONS[@]}" \
 				"${APP_STORE_BUILD_SETTINGS[@]}") || exit 1
 				
+			;;
+			
+		*)
+			echo "error: Unknown build style $STYLE" >&2
+			exit 1
 			;;
 	esac
 done
